spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/indiana_database
    username: admin
    password: 071999
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/